### PR TITLE
Dsmaster

### PR DESCRIPTION
**Pull request by sontek**
@roncohen @nickbruun This merges the latest from datastax master

### CODE REVIEW

**Comment by roncohen** [comment]
Way cool @sontek ! I've managed to actually hook the cpp deserialization up here, if you want to try it: https://github.com/roncohen/python-driver/tree/rons-test

**Comment by sontek** [comment]
@roncohen Nice!  I actually started hacking on that last night =)  I'll pull down that branch

**Comment by sontek** [comment]
@roncohen Significant improvement =)

Before:

```
$ time python single2.py 
102326

real    0m4.334s
user    0m1.877s
sys 0m0.050s
```

with `rons-test`:

```
time python single2.py 
102326

real    0m3.811s
user    0m0.237s
sys 0m0.085s
```

**Comment by roncohen** [comment]
Interesting! What does `single2.py` do exactly? I expect most speedup to come from big rows with lots of data.

Did you look for `Using pure python deserialization` to make sure it's using the optimized version?

**Comment by sontek** [comment]
@roncohen I have 2 operations that I'm testing, both involve pulling back large sets of rows (100,000 rows and 2 million rows).  single2.py just grabs 100,000 rows.   I'm pretty sure its using the new C code because my 2 million row operation went from 10 seconds to 3.9 seconds in performance.

Before:

```
python multi_hour.py 
--- 10.766704082489014 seconds ---
```

After:

```
python multi_hour.py 
--- 3.94518518448 seconds ---
```

**Comment by sontek** [comment]
@roncohen I'll start sending PRs to rons-test instead of feature/fast

**Pull request closed without merging**
